MySQL:
  # 这个地址是docker里面的地址
  Host: moviespider_mysql
  Port: 3306
  Database: movie
  User: root
  Password: P@ssw0rd

Douban:
  # 豆瓣电影想看清单，替换成自己的清单
  DoubanUrl: "https://movie.douban.com/people/251312920/wish"
  Scheduling: "*/10 * * * *"
  # 豆瓣电影 公共API
  WMDBPrefix: "https://api.wmdb.tv/movie/api?id="
Feed:
  # 代理池 这里使用 https://github.com/jhao104/proxy_pool,  在readme中搜索 关键词 jhao104/proxy_pool
  ProxyPool: "http://127.0.0.1:5010"
  BTBT:
    Url: https://www.btbtt12.com/forum-index-fid-951.htm
    Scheduling: "*/5 * * * *"
  EZTV:
    Scheduling: "*/5 * * * *"
    Url: "https://eztv.re/ezrss.xml"
  GLODLS:
    Scheduling: "*/3 * * * *"
    Url: "https://glodls.to/rss.php?cat=1,41"
  RARBG:
    - Scheduling: "*/3 * * * *"
      Url: "http://rarbg.to/rssdd.php?categories=14;15;16;17;21;22;42;44;45;46;47;48"
      ResourceType: movie
    - Scheduling: "*/2 * * * *"
      Url: "http://rarbg.to/rssdd.php?categories=18;19;41"
      ResourceType: tv
  KNABEN:
    Url: "https://rss.knaben.eu"
  Bt4G:
    Url: "https://bt4g.org"

Global:
  LogLevel: info

# Downloader 下载
Downloader:
  Scheduling: "*/10 * * * *"
  # 使用哪个 Aria2 下载
  Aria2Label: "home"

# Aria2 下载服务器
Aria2cList:
  - Url: "http://127.0.0.1e:6800"
    Token: P@ssw0rd
    Label: home

# 如果没有Telegram 就请忽略
#TG:
  # Telegram 网络代理
#  Proxy:
#    Url: socks5://127.0.0.1:1080
#    Enable: false
  # Telegram 机器人 token
#  BotToken: "TOKEN"
#   能正常访问机器人的Telegram用户
#  TgIDs: [ 123456 ]
